name: Linklist Release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  docs-build:
    name: Create README PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish PDF Document
        uses: BaileyJM02/markdown-to-pdf@v1
        id: publish-document
        with:
          input_path: 'README.md'
          output_dir: pdfs
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: doc-artifact
          path: pdfs/README.pdf
          retention-days: 1

  create-release:
    name: Create Release (${{ matrix.os }})
    needs: docs-build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set Output Directory
        uses: mathiasvr/command-output@v1
        id: outdir_name
        with:
          run: echo $GITHUB_REPOSITORY | cut -d '/' -f 2 | cut --complement -f1 -d '-' | xargs
      - name: Set Version Suffix
        uses: mathiasvr/command-output@v2.0.0
        id: outver
        with:
          run: |
            VERSION="${{ steps.previoustag.outputs.tag }}"
            VERSION_STR=$(${VERSION//./_} | xargs)
            echo "${VERSION_STR}_${{ matrix.os }}"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Retrieve saved Docker image
        uses: actions/download-artifact@v3
        id: download
        with:
          name: doc-artifact
          path: README.pdf
      - name: Create Package
        run: |
          sudo apt install zip -y
          DIR_NAME=$(echo "${{ steps.outdir_name.outputs.stdout }}" | xargs)_$(echo "${{ steps.outver.outputs.stdout }}" | xargs)
          DIR_NAME=$(echo $DIR_NAME | xargs)
          cp ${{steps.download.outputs.download-path}} $DIR_NAME/README.pdf
          cp target/release/linklist $DIR_NAME
          zip -r $DIR_NAME.zip $DIR_NAME
          ls *.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: ${{ github.repository }} Release ${{ steps.previoustag.outputs.tag }}
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: |
            *.zip