name: linklist

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        components: llvm-tools-preview

    - name: Run Tests
      uses: Swatinem/fucov@v1
    - uses: codecov/codecov-action@v2
      with:
        env_vars: OS
        directory: coverage